-- Import the 20 initial meals into the database as published.
-- Paste this into the Neon SQL console after running db/schema.sql.

INSERT INTO meals (id, name, description, meal_slot_allowed, category, main_protein, protein_group, carb_base, meal_style, fruit_or_veg, tags, emoji, status) VALUES
('meal_001', 'Berry Parfait', 'Layers of silky Greek yogurt, house-made honey granola, and seasonal wild berries.', ARRAY['breakfast','snack_am','snack_pm'], 'dairy_sweet_bowl', 'yogurt', 'dairy', 'granola', ARRAY['sweet','bowl'], 'fruit', ARRAY['LOW SUGAR'], '🫐', 'published'),
('meal_002', 'Avocado Toast', 'Sourdough bread topped with creamy smashed avocado, chili flakes, and a perfectly poached egg.', ARRAY['breakfast','lunch'], 'eggs_savory', 'eggs', 'eggs', 'bread', ARRAY['savory','sandwich'], 'veg', ARRAY['VEGGIE','PROTEIN'], '🥑', 'published'),
('meal_003', 'Almond Oats', 'Rolled oats soaked in almond milk with chia seeds, topped with sliced banana and toasted almonds.', ARRAY['breakfast'], 'oats_porridge', 'nuts', 'nuts_seeds', 'oats', ARRAY['sweet','bowl'], 'fruit', ARRAY['DAIRY-FREE'], '🥣', 'published'),
('meal_004', 'Scrambled Eggs on Toast', 'Fluffy scrambled eggs with fresh herbs on toasted whole grain bread.', ARRAY['breakfast','lunch'], 'eggs_savory', 'eggs', 'eggs', 'bread', ARRAY['savory','sandwich'], 'none', ARRAY['PROTEIN'], '🍳', 'published'),
('meal_005', 'Protein Smoothie Bowl', 'Blended protein powder with frozen mango and banana, topped with coconut and seeds.', ARRAY['breakfast','snack_am'], 'dairy_sweet_bowl', 'protein_powder', 'supplement_protein', 'fruit', ARRAY['sweet','bowl'], 'fruit', ARRAY['PROTEIN','DAIRY-FREE'], '🥤', 'published'),
('meal_006', 'Nuts & Fruit Mix', 'A balanced handful of almonds, walnuts, dried cranberries, and dark chocolate chips.', ARRAY['snack_am','snack_pm'], 'nuts_fruit_snack', 'nuts', 'nuts_seeds', 'fruit', ARRAY['sweet','light'], 'fruit', ARRAY['DAIRY-FREE'], '🥜', 'published'),
('meal_007', 'Cheese & Crackers', 'Aged cheddar with whole grain crackers and a drizzle of honey.', ARRAY['snack_am','snack_pm'], 'cheese_savory', 'cheese', 'dairy', 'bread', ARRAY['savory','light'], 'none', ARRAY['PROTEIN'], '🧀', 'published'),
('meal_008', 'Apple & Peanut Butter', 'Crisp apple slices with a generous serving of natural peanut butter.', ARRAY['snack_am','snack_pm'], 'nuts_fruit_snack', 'nuts', 'nuts_seeds', 'fruit', ARRAY['sweet','light'], 'fruit', ARRAY['DAIRY-FREE','VEGGIE'], '🍎', 'published'),
('meal_009', 'Yogurt with Honey', 'Creamy Greek yogurt drizzled with raw honey and a sprinkle of cinnamon.', ARRAY['snack_am','snack_pm','breakfast'], 'dairy_sweet_bowl', 'yogurt', 'dairy', 'none', ARRAY['sweet','bowl'], 'none', ARRAY['LOW SUGAR','PROTEIN'], '🍯', 'published'),
('meal_010', 'Hummus & Veggies', 'Smooth chickpea hummus with carrot sticks, cucumber, and bell pepper.', ARRAY['snack_am','snack_pm'], 'protein_snack', 'legumes', 'plant', 'none', ARRAY['savory','light'], 'veg', ARRAY['VEGGIE','DAIRY-FREE'], '🥕', 'published'),
('meal_011', 'Grilled Chicken Salad', 'Tender grilled chicken breast over mixed greens with cherry tomatoes and balsamic.', ARRAY['lunch','dinner'], 'meat_fish_main', 'chicken', 'meat', 'none', ARRAY['savory','salad'], 'veg', ARRAY['PROTEIN'], '🥗', 'published'),
('meal_012', 'Lentil Soup', 'Hearty red lentil soup with cumin, carrots, and a squeeze of lemon.', ARRAY['lunch','dinner'], 'legume_main', 'legumes', 'plant', 'none', ARRAY['savory','bowl'], 'veg', ARRAY['VEGGIE','DAIRY-FREE'], '🍲', 'published'),
('meal_013', 'Tuna Wrap', 'Light tuna salad in a whole wheat wrap with lettuce, tomato, and avocado.', ARRAY['lunch'], 'meat_fish_main', 'fish', 'fish', 'bread', ARRAY['savory','sandwich'], 'veg', ARRAY['PROTEIN'], '🌯', 'published'),
('meal_014', 'Veggie Buddha Bowl', 'Roasted sweet potato, quinoa, chickpeas, and tahini dressing over greens.', ARRAY['lunch','dinner'], 'plant_main', 'legumes', 'plant', 'rice', ARRAY['savory','bowl','main_meal'], 'veg', ARRAY['VEGGIE','DAIRY-FREE'], '🥙', 'published'),
('meal_015', 'Egg & Cheese Plate', 'Soft-boiled eggs with sliced cheese, mixed greens, and whole grain bread.', ARRAY['lunch'], 'egg_cheese_salad', 'eggs', 'eggs', 'bread', ARRAY['savory','salad'], 'veg', ARRAY['PROTEIN'], '🥚', 'published'),
('meal_016', 'Salmon with Rice', 'Pan-seared salmon fillet with steamed jasmine rice and roasted broccoli.', ARRAY['dinner','lunch'], 'meat_fish_main', 'fish', 'fish', 'rice', ARRAY['savory','main_meal'], 'veg', ARRAY['PROTEIN'], '🐟', 'published'),
('meal_017', 'Chicken Stir-fry', 'Wok-tossed chicken with colorful vegetables, ginger, and soy sauce over rice.', ARRAY['dinner'], 'meat_fish_main', 'chicken', 'meat', 'rice', ARRAY['savory','main_meal'], 'veg', ARRAY['PROTEIN'], '🍗', 'published'),
('meal_018', 'Tofu Curry', 'Golden tofu in a creamy coconut curry with spinach, served over basmati rice.', ARRAY['dinner','lunch'], 'plant_main', 'tofu', 'plant', 'rice', ARRAY['savory','main_meal'], 'veg', ARRAY['VEGGIE','DAIRY-FREE'], '🍛', 'published'),
('meal_019', 'Pasta Primavera', 'Penne with sauteed seasonal vegetables in a light garlic olive oil sauce.', ARRAY['dinner','lunch'], 'plant_main', 'cheese', 'dairy', 'pasta', ARRAY['savory','main_meal'], 'veg', ARRAY['VEGGIE'], '🍝', 'published'),
('meal_020', 'Bean & Vegetable Stew', 'Slow-cooked white beans with tomatoes, zucchini, and fresh herbs.', ARRAY['dinner','lunch'], 'legume_main', 'legumes', 'plant', 'none', ARRAY['savory','bowl','main_meal'], 'veg', ARRAY['VEGGIE','DAIRY-FREE'], '🫘', 'published')
ON CONFLICT (id) DO NOTHING;
